root: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  es6: true
  browser: true
  node: true

plugins:
  - import
  - prettier

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - xo
  - prettier

rules:
  react/prop-types: off
  react/react-in-jsx-scope: off

settings:
  react:
    version: detect

overrides:
  - files:
      - '**/test/**/*.js'
    rules:
      import/no-unresolved: off
  - files:
      - '*.d.ts'
      - '**/types/*.ts'
      - '**/types/*.tsx'
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-unused-vars': off
      '@typescript-eslint/no-explicit-any': off
      capitalized-comments: off
      no-unused-vars: off
      no-unused-expressions: off
      no-redeclare: off
